import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export const ENGLISH_TRANSLATION = {
  languageLogo: "http://purecatamphetamine.github.io/country-flag-icons/3x2/US.svg",
  landingAgm: "Annual General Meeting (AGM) is a multi-day in-person event for all of our members during Thanksgiving break every year.",
  landingBuop: "Best University Opportunity Program (BUOP) is an annual summer college prep program for high school students.",
  landingMentorship: "Our mentoship programs connect high school, college students and working professionals. Our Podcasts cover topics concerning our members in the US.",
  mentorshipPodcast: "Mentorship & Podcast",
  myClass: "My Class",
  comments: "Comments",
  post: "Post",
  logout: 'Log out',
  admin: 'Admin',
  myAccount: 'My account',
  home: 'Home',
  articles: 'Articles',
  intro: 'Association of Mongolian Students in America (AMSA) connects over 600 Mongolian students across the US. We organize annual and seasonal events around mentorship, networking and career opportunities.',
  ourProjects: 'Our Projects',
  team: 'Team',
  ourTeam: 'Our Team',
  ourTeamDesc: 'Our executive board is elected from the current member students every year.',
  donationBox: 'Donation',
  caseCompetition: 'ACT Career Training Program',
  theme: 'Theme',
  search: 'Type to search',
  joinAMSA: 'Join AMSA',
  agm: 'AGM',
  recentArticles: 'Recent Articles',
  amsaSong: 'AMSA song',
  contact: 'Contact Us',
  about: 'About Us',
  amsa: 'AMSA',
  readMore: 'Read more',
  buop: 'BUOP',
  podcasts: 'Podcasts',
  inspirationHour: 'Inspiration hour',
  nonAcademicActivity: 'Non-academic activity',
  executiveMembers: 'Executive Board Members',
  toBeAnnounced: 'To be announced',
  register: 'Register',
  login: 'Login',
  amsaMember: 'AMSA member',
  guest: 'Guest',
  back: 'Back',
  accountInfo: 'Account info',
  personalInfo: 'Personal info',
  schoolInfo: 'School Info',
  socialMediaInfo: 'Social Info',
  password: 'Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  personalEmail: 'Personal email',
  phone: 'Phone',
  birthDate: 'Birth date',
  address: 'Address',
  city: 'City',
  state: 'State',
  zipCode: 'ZIP code',
  next: 'Next',
  schoolName: 'School Name',
  pursuingDegree: 'Pursuing degree',
  graduationYear: 'Graduation year',
  schoolYear: 'School year',
  major: 'Major',
  secondMajor: 'Second major',
  verify: 'Verify',
  signUp: 'Sign-up',
  inception: 'Inception',
  mission: 'Mission',
  accomplishments: 'Accomplishments',
  goals: 'Goals',
  buop_main_1: 'The goal of the Best University Opportunity Program is to help Mongolian students study in the United States for bachelor’s and master’s degrees. BUOP has been organized every summer since 2010 and is taught by Mongolian students studying in prestigious US colleges and universities. We believe being taught by those who successfully went through the application process would be of great help to our students since the US college admission process is very different from that of Mongolian. Moreover, BUOP would not only help you prepare for your college application but also be a great source to know about US college life, such as college classes, cultural differences, student clubs, and so on.',
  buop_main_2: 'One of the most important characteristics of BUOP is that we offer scholarships for students with financial hardship. We believe that students’ access to education should be independent of their financial situation, so every year we fundraise among our members and use their donation to relieve our students from financial difficulties. ',
  buop_main_3: 'BUOP curriculum consists of classes needed to apply for bachelor’s and master’s degrees in the US and non-academic activities.',
  undergrad_app: 'This course teaches students about how to apply for a bachelor’s degree, how to prepare the required materials, such as personal essays, recommendation letters, supplement essays, and school selection, and how the college admission officers make their decisions.',
  toefl: 'TOEFL is a standardized test that all international students must take to show their proficiency in English unless they went to a high school taught in English. This course is based on practice tests to help students improve their 4 main language skills (reading, listening, speaking, and writing) and teach techniques and methods they could use. ',
  pre_toefl: 'This course is to help students get ready to start preparing for TOEFL. During the program, students would learn advanced grammars and build the foundations of the 4 main language skills (reading, listening, speaking, and writing). If you think you’re not ready to take TOEFL or not confident in yourself, this course is for you.',
  sat_reading: 'This course prepares students for the reading section of SAT Reasoning and teaches them the techniques that could help to get high scores. Compared to other tests, SAT reading examines students’ critical thinking skills, which might make the test hard for most students, but with the right guidance and technique, it’s possible to get high scores.',
  sat_writing: 'The inseparable part of SAT Reasoning is the Writing & Language section which tests the common daily mistakes we make in our writing. In this course, students will learn about many grammar that we use incorrectly and many more that we never learned in school.',
  inspiration_hour: 'Every week students are invited to attend a talk by our members and learn from their experiences. Inspiration hour is designed to be accessible for every BUOP student no matter how many classes they are enrolled in. ',
  non_academic: 'At BUOP, we create opportunities for our students to make friends and learn from their peers and teachers by participating in our weekly fun non-academic events. This is an excellent opportunity for students to get to know their teachers and peers at a personal level and develop a sense of belonging. ',
  grad_app: 'This course teaches students about how to apply for a master’s and doctoral degree, how to prepare the required materials, such as personal essays, recommendation letters, supplement essays, and school selection, and how the college admission officers make their decisions.',
  academic_label: 'Academic courses',
  non_academic_label: 'Non-academic curriculum',
  sb: 'Strategy Board',
  donation_text_1: 'Every summer the Association of Mongolian Students in America organizes the "Best University Opportunity Program" which provides middle and high school students as well as young professionals with the tools and knowledge that they need to pursue higher education in the US.',
  donation_text_2: 'One of our goals is to advance educational equity in Mongolia by providing up to 100 promising students from low income families with an opportunity to receive scholarships and take classes of their choices at BUOP. BUOP scholarship recipients are selected based on their applicant’s academic excellence, extracurricular activities, determination, and financial background. Each student is given personal attention and made sure that they are surrounded by brilliant ambitious students and teachers.',
  donation_text_3: 'To this end, we ask that you take part in our cause and help students achieve their goals of furthering their education in the US. Thank you for your generosity.',
  mission_text: 'The goal of the not for profit and non-governmental organization the Association of Mongolian Students in America (AMSA) is to create a network of outstanding Mongolian alumni and students pursuing bachelor’s degrees or higher in the United States and to initiate and implement projects that advance education and economic equity.',
  inception_text: 'The AMSA was founded by 7 Mongolian college students from Harvard, Wesleyan, Mount Holyoke, MIT, and Columbia in November 2011. Now the association has over 600 members in 48 states.',
  accomplishment_text: 'Since the founding of the association, the AMSA has worked with numerous private and governmental organizations such as the Permanent Mission of Mongolia to the United Nations and Oyu Tolgoi to provide help and resources to our members and the general public. One of our biggest accomplishments is the successful initiation and organization of the Best University of Opportunity Program (BUOP), a summer program designed to prepare Mongolian students and young professionals to enroll in undergraduate and graduate schools in the United States. We have organized this program for 10 consecutive years and helped over 1300 students achieve their goals.',
  agm_text_main: 'Annual General Meeting (AGM) is a two-day members only conference organized by the AMSA during the Thanksgiving break. Each year the event is organized at different colleges in the US. The AGM allows AMSA members to network and grow professionally and personally. The very first AGM was held at MIT and Harvard in Massachusetts in Nov, 2012. Since then we have organized the event at the following locations:',
  agm_text_1: '2013 - MIT and Harvard, MA',
  agm_text_2: '2014 - New York University, NY',
  agm_text_3: '2015 - University of Michigan,MI',
  agm_text_4: '2016 - Georgia Institute of Technology, GA',
  agm_text_5: '2017 - The University of Chicago, IL',
  agm_text_6: '2018 - New York University, NY',
  agm_text_7: '2019 - University of Colorado Boulder, CO',
  agm_text_8: '2020 - Due to Covid-19 restrictions, we organized our event online attracting participants outside of the US.',
  agm_text_9: '2021 - MIT, MA',
  agm_text_10: '2022 - Mongolian Embassy in Washington, DC',
  agm_text_11: '2023 - UC Berkeley / Silicon Valley, CA',
  agm_text_12: '2024 - TBD'
}

export const MONGOLIAN_TRANSLATION = {
  languageLogo: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MN.svg",
  landingAgm: "Нэгдсэн Чуулга Уулзалт нь жил бүр 2-3 өдрийн туршид зохион байгууллагддаг.",
  landingBuop: "Best University Opportunity Program (BUOP) зуны хөтөлбөр нь их дээд сургуулиудад амжилттай өргөдлөө явуулхад тусалдаг.",
  landingMentorship: "Мэнторшип хөтөлбөр нь дунд болон их сургуулийн сурагч нарыг холбохоос гадна ажлын талбар дээр гарсан төгсөгс нарыг гишүүдтэйгээ холбодог.",
  myClass: "Манай анги",
  comments: "Сэтгэгдлүүд",
  post: "Илгээх",
  logout: 'Гарах',
  admin: 'Admin',
  myAccount: 'My account',
  home: 'Нүүр хуудас',
  articles: 'Нийтлэлүүд',
  intro: 'Бид 600 гаруй Монгол оюутан залуусыг Америк даяар холбодог ТББ юм. Мэргэжлийн карер, мэнторшип, нэтворкинг зэрэг арга хэмжээнүүдийг жил бүр тогтмол зохион байгуулдаг.',
  ourProjects: 'Төслүүд',
  mentorshipPodcast: "Менторшип & Подкаст",
  team: 'Баг',
  ourTeam: 'ТУЗ',
  ourTeamDesc: 'Төлөөлөн Удирдах Зөвлөлийн (ТУЗ) 7 гишүүн жил бүр гишүүдээс сонгогддог.',
  donationBox: 'Xандив',
  caseCompetition: 'ACT Career Training Program',
  theme: 'Theme',
  search: 'Хайх зүйлсээ оруулна уу',
  joinAMSA: 'АМОХ-д нэгдэх',
  agm: 'НЧУ',
  recentArticles: 'Шинэ нийтлэлүүд',
  amsaSong: 'АМОХ-н дуу',
  contact: 'Бидэнтэй холбогдох',
  about: 'Танилцуулга',
  amsa: 'АМОХ',
  readMore: 'Цааш унших',
  buop: 'БУОП',
  podcasts: 'Подкастууд',
  inspirationHour: 'Inspiration hour',
  nonAcademicActivity: 'Академик бус үйл ажиллагаа',
  executiveMembers: 'Удирдах зөвлөлийн гишүүд',
  toBeAnnounced: 'Удахгүй зарлагдах болно',
  register: 'Бүртгүүлэх',
  login: 'Нэвтрэх',
  amsaMember: 'АМОХ-н гишүүн',
  guest: 'Зочин',
  back: 'Буцах',
  accountInfo: 'Бүртгэлийн мэдээлэл',
  personalInfo: 'Xувийн мэдээлэл',
  schoolInfo: 'Cургуулийн мэдээлэл',
  socialMediaInfo: 'Social Info',
  password: 'Hууц үг',
  firstName: 'Hэр',
  lastName: 'Oвог',
  personalEmail: 'Xувийн и-майл хаяг',
  phone: 'Утасны дугаар',
  birthDate: 'Tөрсөн өдөр',
  address: 'Xаяг',
  city: 'Xот',
  state: 'Mуж',
  zipCode: 'Бүсийн код (ЗИП код)',
  next: 'Дараах',
  schoolName: 'Сургууль',
  pursuingDegree: 'Эзэмшиж буй мэргэжил',
  graduationYear: 'Tөгсөх он',
  schoolYear: 'Kурс',
  major: 'Mэргэжил',
  secondMajor: 'Давхар мэргэжил',
  verify: 'Баталгаажуулах',
  signUp: 'Бүртгүүлэх',
  inception: 'Эхлэл',
  mission: 'Зорилт',
  accomplishments: 'Амжилтууд',
  goals: 'Зорилго',
  buop_main_1: 'Best University Opportunity Program (БУОП) нь Америкийн Нэгдсэн улсад бакалавр, магистрийн зэргээр суралцах хүсэлтэй залууст туслах зорилготой програм юм. БУОП нь 2010 оноос эхлэн зун бүр зохион байгуулагдсан бөгөөд АНУ-н шилдэг их дээд сургуулиудад сурдаг Монгол оюутнууд маань зуны амралтаараа заадгаараа онцлогтой. Америкийн их сургуулийн элсэлтийн систем нь Монголынхоос маш өөр тул өргөдлөө амжилттай явуулаад тэнцсэн хүнээр заалгах нь хамгийн үр дүнтэй байдаг. БУОП нь ганцхан өргөдлөө бэлдэхэд туслахаас гадна мөн их сургуулийн хичээл, соёлын ялгаа, сургуулийн кампус, сурагчдын клуб гэх мэтчилэн Америк дах оюутны амьдралын талаар илүү мэдээлэлтэй болох боломжтой байдаг.',
  buop_main_2: 'Мөн БУОП-н өөр нэг хамгийн чухал онцлог нь сурагчиддаа тэтгэлэг олгодог явдал юм. Бид сурагчдын боловсрол эзэмших боломж нь санхүүгийн байдлаас нь хараат бус байх хэрэгтэй гэж боддог тул гишүүдээсээ босгосон хандиваараа жил бүр тодорхой тооны сурагчдад тэтгэлэг олгодог. ',
  buop_main_3: 'БУОП програмын хөтөлбөр нь Америкд бакалавр, магистраар өргөдлөө явуулахад хэрэгтэй бүх төрлийн хичээлүүд болон академик бус үйл ажиллагаа гэсэн хэсгүүдээс бүрддэг. ',
  undergrad_app: 'Энэ хичээл нь бакалаврийн зэргийн өргөдлийн процесс хэрхэн явагддаг, шаардлагатай материалуудыг (эсээ, багшийн тодорхойлолт, нэмэлт эсээнүүд, сургууль сонголт гэх мэтчилэнг) хэрхэн бэлдэх болон мөн элсэлтийн албаныхан сурагчдаа хэрхэн сонгож авдаг талаар заадаг. ',
  toefl: 'TOEFL нь олон улсын сурагчдын өгөх ёстой стандарт шалгалтуудын нэг бөгөөд англи хэлний мэдлэг шалгах ярих, сонсох, унших, бичих хэсгүүдээс бүрддэг. Энэ хичээл нь дадлага тестүүд дээр суурилан шалгалтын арга барил, техникийг заадаг.',
  pre_toefl: 'Энэ анги нь iBT-TOEFL-ын шалгалтад бэлдэх үеийн өмнөх шат юм. Сургалтын явцад англи хэлний ахисан шатны дүрмүүд болон англи хэлний эсээ бичих чадварыг эхнээс нь олгохоос гадна TOEFL-ын шалгалтад бэлтгэх хялбар материалууд дээр суурилан явагддагаараа онцлогтой юм. Хэрвээ та өөрийгөө TOEFL-д бэлдэхэд арай бэлэн биш гэж бодож байвал энэ хичээлийг сонирхоод үзээрэй.',
  sat_reading: 'Энэ хичээл нь SAT Reasoning шалгалтын Reading хэсэгт бэлдэх арга барил болон өндөр авахад туслах техникүүдээс заана. SAT Reading нь бусад шалгалттай харьцуулбал шүүмжит сэтгэлгээг илүүтэйгээр шалгадаг тул ихэнх сурагчдад арай хэцүү санагддаг талтай ч зөв арга барилаар өндөр оноо авах боломжтой шалгалт юм.',
  sat_writing: 'SAT шалгалтын нэгэн салшгүй хэсэг нь Writing & Language буюу байнга тохиолддог дүрмийн хэрэглээг шалгадаг хэсэг юм. Бидний зөв гэж боддог ч буруу хэрэглэдэг эсвэл заримдаа байдгийг нь ч мэдээгүй байсан олон дүрмийг энэ хичээл дээр сурах боломжтой.',
  inspiration_hour: 'Бид долоо хоногт нэг удаа сурагчиддаа урам зориг, мотивац өгөх зорилгоор Америкийн шилдэг их дээд сургуулиудад сурдаг оюутнууд болон Америкт ажилдаг Монголчуудаасаа урин, тэдний түүх, туршлагыг хуваалцан ярилцдаг.',
  non_academic: 'Сурагчдаа хичээлээс гадуур хооронд нь болон багш нартай нь илүү сайн танилцуулах зорилгоор долоо хоногт нэг удаа академик бус үйл ажиллагаа зохион байгуулдаг. Энэ нь манай сурагчдад хоорондоо хичээлийн бус сэдвээр ярилцан эсвэл тоглоом тоглон бие биенээ илүү сайн таниж мэдэх боломж болдог.',
  grad_app: 'АНУ-д Graduate сургууль буюу Мастер, Докторын зэргээр хэрхэн элсэх талаар мэдээлэл болон туршлагаа АНУ-ын шилдэг их дээд сургуульд Докторын зэргээр суралцах гэж байгаа багш өөрийн хэрхэн тэнцсэн туршлагаа хуваалцах болно.',
  academic_label: 'Академик хөтөлбөр',
  non_academic_label: 'Академик бус хөтөлбөр',
  sb: 'Бодлогын Зөвлөл',
  donation_text_1: 'Америк Дахь Монгол Оюутны Xолбоо нь ашгийн бус байгууллага бөгөөд жил бүр Америкийн нэгдсэн улсруу суралцахаар зориж буй хүүхэд залуучуудад зориулан  БУОП хөтөлбөрийг зохион байгуулдаг байгаа.',
  donation_text_2: 'Энэхүү хөтөлбөртөө бид мэдлэг чадвар, санхүүгийн боломж болон хүсэл зорилго дээр нь үндэслэн жил бүр тодорхой тооны хүүхдүүдийг шалгаруулан 25%, 50%, 75%, болон 100%ийн сургалтын тэтгэлгийг өгдөг билээ. Жил бүр цугларсан нийт хандивын мөнгөн дүнгээс харгалзан тухайн жилд хэдэн хүүхдэд тэтгэлэг өгөх нь тодорхойлогддог бөгөөд 2020 оны хөтөлбөртөө бид нийт 3000$ цуглуулан 100-н хүүхдэд тэтгэлэг өгч чадсан билээ.',
  donation_text_3: 'Таны өнөөдрийн өгөх хандив Монголын ирээдүй болсон залуучуудад өндөр боловсролтой болоход нь туслах гүүр нь байх болно.',
  mission_text: 'Америк дахь Монгол Оюутны Холбоо (АМОХ) төрийн бус байгууллагын зорилго нь Америкийн  Нэгдсэн Улс дахь Монголын шилдэг оюутан,  төгсөгчидийг хамарсан сүлжээ, тэдгээрийн мэдээллийн  санг бий болгож улмаар Монгол улсад болон олон  улсад боловсрол, эдийн засаг, улс төрийн болон сайн  санааны үйлс зохион байгуулж оролцох юм.',
  inception_text: 'Америк дахь Монгол Оюутны Холбоо (АМОХ)-г Harvard, Wesleyan, Mount Holyoke, MIT, Columbia гэх мэт их сургуулиудын долоон Монгол оюутан залуус 2011 оны 11 дүгээр сард үүсгэн байгуулсан юм. АМОХ нь Америкийн 48 мужид бакалавр болон түүнээс дээш зэргээр суралцаж төгссөн болон бол одоогоор суралцаж болон буй 600 гаруй гишүүдтэй.',
  accomplishment_text: 'Өнгөрсөн хугацаанд АМОХ нь жил бүр үйл ажиллагаагаа тасралтгүй явуулж Америк болон Монголд суугаа элчин сайдын яамдууд болон Монгол хувийн хэвшлийн томоохон компаниудтай хамтран ажиллаж холбооны зорилгийн хүрээнд ажиллаж ирсэн. Бидний томоохон амжилтуудаас дурдвал 10 жилийн туршид бид зун бүр БУОП буюу Best University Opportunity хөтөлбөрийг зохион байгуулж нийт 1300 гаруй ахлах болон дунд ангийн сурагчдад мөн түүнчлэн залуу ажилчдад АНУ-д хэрхэн бакалавр болон мастерын зэрэг горилон сурах талаар цогц хичээлүүдийг зааж сурагсан явдал юм.',
  agm_text_main: 'АМОХ-ны бүх гишүүдийн чуулга уулзалт нь жил бүрийн 11 сард Америкийн их сургуулиуд дээр 2 өдрийн турш зохион байгууллагддаг уламжлалтай.  Энэхүү уулзалт нь гишүүдэд бусадтайгаа мэдлэг солилцох нэг нэгнээсээ суралцах боломжийг олгодог. Хамгийн анхны чуулга уулзалт нь  2012 оны 11 сарын 23, 24 -ны өдрүүдэд Массачүсэтс мужийн Кэмбридж хотноо MIT болон Harvard-н их сургуулиуд дээр зохион байгуулагдаж байсан түүхтэй. Түүнээс хойш бүх гишүүдийн чуулга уулзалт нь:',
  agm_text_1: '2013 онд дахин Массачүсэтс мужийн Кэмбридж хотноо MIT болон Harvard-н Их Сургууль',
  agm_text_2: '2014 онд Нью-Йорк мужийн Нью-Йорк хотноо Нью-Йоркийн Их Сургууль',
  agm_text_3: '2015 онд Мичиган мужийн Анн Арбор хотноо Мичиганы Их Сургууль',
  agm_text_4: '2016 онд Жеоржиа мужийн Атланта хотноо Жеоржиа Mужийн Технологийн Их Сургууль',
  agm_text_5: '2017 онд Иллинойс мужийн Чигагогын Их Сургууль',
  agm_text_6: '2018 онд Нью-Йорк мужийн Нью-Йорк хотноо Нью-Йоркийн Их Сургууль',
  agm_text_7: '2019 онд Колорадо мужийн Колорадогын Их Сургууль',
  agm_text_8: '2020 онд анх удаагаа онлайнаар зөвхөн АНУ-д бус Монголд суугаа гишүүдийг хамарсан чуулга уулзалтыг зохион байгуулсан',
  agm_text_9: '2021 онд дахин Массачүсэтс мужийн Кэмбридж хотноо MIT Их Сургууль',
  agm_text_10: '2022 онд Вашингтон хотын Монгол Улсын Элчин Сайдийн Яам',
  agm_text_11: '2023 онд Калифорниа мужийн ЮҮ-Си Беркели Их Сургууль болон Цахиурын Хөндийд',
  agm_text_12: '2024 оны зар удахгүй тавигдах болно',
}

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private _currentLanguage: BehaviorSubject<string> = new BehaviorSubject<string>('english');
  currentLanguage = this._currentLanguage.asObservable();
  private _translationText = new BehaviorSubject(ENGLISH_TRANSLATION);
  currentTranslationText = this._translationText.asObservable();

  constructor() { }

  setLanguage(language: string) {
    if (language === 'mongolian') {
      this._translationText.next(MONGOLIAN_TRANSLATION);
    } else {
      this._translationText.next(ENGLISH_TRANSLATION);
    }
    this._currentLanguage.next(language);
  }

  getCurrentLanguage() {
    return this._currentLanguage.value;
  }

  toggleLanguage() {
    if (this._currentLanguage.value === 'mongolian') {
      this._translationText.next(ENGLISH_TRANSLATION);
      this._currentLanguage.next('english');
    } else {
      this._translationText.next(MONGOLIAN_TRANSLATION);
      this._currentLanguage.next('mongolian');
    }
  }
}
